---
abstract: 'Perinci example scripts'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-Examples-Bin
requires:
  Perinci::CmdLine: 0.67
  Perinci::Examples: 0.14
  Rinci: v1.1.32
  perl: 5.010001
resources:
  homepage: http://metacpan.org/dist/Perinci-Examples-Bin/
  repository: http://github.com/sharyanto/perl-Perinci-Examples-Bin
version: 0.01
